vice 3.8

diff --git a/doc/Makefile.am b/doc/Makefile.am
--- a/doc/Makefile.am
+++ b/doc/Makefile.am
@@ -7,7 +7,8 @@ MISC_DOX = \
 	Doxygen-Howto.txt \
 	iec-bus.txt \
 	Release-Howto.txt \
-	vice.texi
+	vice.texi \
+	gpl.texi
 
 TEXI_TOOLS = \
 	fixdates.sh
@@ -32,9 +33,9 @@ VICE_DOX = @VICE_PDF_FILE_NAME@
 # info_TEXINFOS = vice.texi
 # AM_MAKEINFOFLAGS = -D$(PLATFORM_DOX_FLAGS)
 
-dist_doc_DATA = $(MISC_DOX) $(VICE_DOX)
+dist_doc_DATA = $(VICE_DOX)
 
-EXTRA_DIST = $(DOC_TOOLS) $(TEXI_TOOLS) $(STYLE_TOOLS)
+EXTRA_DIST = $(MISC_DOX) $(DOC_TOOLS) $(TEXI_TOOLS) $(STYLE_TOOLS)
 
 
 if MACOS_COMPILE
@@ -44,8 +45,10 @@ endif
 
 .vice-texi-charset-ok:	$(srcdir)/vice.texi
 	@if [ "`file --mime-encoding $<`" != "$<: iso-8859-1" ]; then \
-		echo "ERROR: vice.texi contains content that is not valid iso-8859-x" >&2; \
-		false; \
+		if [ "`file --mime-encoding $<`" != "$<: us-ascii" ]; then \
+			echo "ERROR: vice.texi contains content that is not valid iso-8859-x" >&2; \
+			false; \
+		fi; \
 	fi
 	@touch .vice-texi-charset-ok
 
diff --git a/doc/Makefile.in b/doc/Makefile.in
--- a/doc/Makefile.in
+++ b/doc/Makefile.in
@@ -281,7 +281,6 @@ GLIB_LIBS = @GLIB_LIBS@
 GTK_CFLAGS = @GTK_CFLAGS@
 GTK_LIBS = @GTK_LIBS@
 HAVE_CXX11 = @HAVE_CXX11@
-HAVE_READLINE = @HAVE_READLINE@
 ICONV = @ICONV@
 ICOTOOL = @ICOTOOL@
 INLINE_UNIT_GROWTH = @INLINE_UNIT_GROWTH@
@@ -328,8 +327,6 @@ PNG_LIBS = @PNG_LIBS@
 PROGRAM_PREFIX = @PROGRAM_PREFIX@
 PROGRAM_SUFFIX = @PROGRAM_SUFFIX@
 RANLIB = @RANLIB@
-READLINE = @READLINE@
-READLINE_LIBS = @READLINE_LIBS@
 RESIDDTVSUB = @RESIDDTVSUB@
 RESIDSUB = @RESIDSUB@
 RESID_DEP = @RESID_DEP@
@@ -354,7 +351,6 @@ SOUND_DRIVERS = @SOUND_DRIVERS@
 SOUND_LIBS = @SOUND_LIBS@
 SOUND_MIDAS_OBJ = @SOUND_MIDAS_OBJ@
 SOUND_SDL_OBJ = @SOUND_SDL_OBJ@
-SOUND_USS_OBJ = @SOUND_USS_OBJ@
 STRIP = @STRIP@
 SVN = @SVN@
 SVNVERSION = @SVNVERSION@
@@ -363,6 +359,7 @@ TAR = @TAR@
 TEXI2DVI = @TEXI2DVI@
 TFE_LIBS = @TFE_LIBS@
 UI_LIBS = @UI_LIBS@
+UNZIPBIN = @UNZIPBIN@
 VERSION = @VERSION@
 VERSION_COMBINED = @VERSION_COMBINED@
 VERSION_RC = @VERSION_RC@
@@ -459,7 +456,8 @@ MISC_DOX = \
 	Doxygen-Howto.txt \
 	iec-bus.txt \
 	Release-Howto.txt \
-	vice.texi
+	vice.texi \
+	gpl.texi
 
 TEXI_TOOLS = \
 	fixdates.sh
@@ -484,8 +482,8 @@ VICE_DOX = @VICE_PDF_FILE_NAME@
 
 # info_TEXINFOS = vice.texi
 # AM_MAKEINFOFLAGS = -D$(PLATFORM_DOX_FLAGS)
-dist_doc_DATA = $(MISC_DOX) $(VICE_DOX)
-EXTRA_DIST = $(DOC_TOOLS) $(TEXI_TOOLS) $(STYLE_TOOLS)
+dist_doc_DATA = $(VICE_DOX)
+EXTRA_DIST = $(MISC_DOX) $(DOC_TOOLS) $(TEXI_TOOLS) $(STYLE_TOOLS)
 
 # This doesn't appear to delete vice.pdf etc added
 # in this Makefile with VICE_DOX += FOO, perhaps just some ordinary `rm -f`
@@ -829,8 +827,10 @@ uninstall-am: uninstall-dist_docDATA
 
 .vice-texi-charset-ok:	$(srcdir)/vice.texi
 	@if [ "`file --mime-encoding $<`" != "$<: iso-8859-1" ]; then \
-		echo "ERROR: vice.texi contains content that is not valid iso-8859-x" >&2; \
-		false; \
+		if [ "`file --mime-encoding $<`" != "$<: us-ascii" ]; then \
+			echo "ERROR: vice.texi contains content that is not valid iso-8859-x" >&2; \
+			false; \
+		fi; \
 	fi
 	@touch .vice-texi-charset-ok
 
